#Project :Chemical segergration

In [1]:
import pandas as pd

In [2]:
X_train = pd.read_csv('/content/Logistic_X_Train.csv')
y_train = pd.read_csv('/content/Logistic_Y_Train.csv')

### X_train (Features) Data Overview

In [6]:
display(X_train.head())

         f1        f2        f3
0 -1.239375  0.749101 -0.528515
1 -1.036070  0.801436 -1.283712
2 -0.615579  1.579521 -1.391927
3  1.335978  1.348651  1.433564
4  0.658925  1.300019  0.571603

### y_train (Target) Data Overview

In [4]:
display(y_train.head())

   label
0      1
1      1
2      1
3      0
4      0